{% set name = "ase" %}
{% set version = "3.15.0" %}
{% set sha256 = "5e22d961b1311ef4ba2d83527f7cc7448abac8cf9bddd1593bee548459263fe8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: 
    - ngl_fix.patch

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - flask 0.10.*  # [py<36]
    - flask  # [py>=36]
    - matplotlib
    - scipy
  run:
    - python
    - flask 0.10.*  # [py<36]
    - flask  # [py>=36]
    - matplotlib
    - numpy 
    - scipy

test:
  imports:
    - ase
  commands:
    - export DISPLAY=""   # [not win]
    - ase test


about:
  home: https://gitlab.com/ase/ase
  license: LGPL-2.1+
  license_file: LICENSE
  summary: 'ASE is a python package providing an open source Atomic Simulation Environment in the Python language.'

  description: |
    ASE is a set of tools and Python modules for setting up, 
    manipulating, running, visualizing and analyzing atomistic simulations.
    Python 2.6-3.6 
  doc_url: http://wiki.fysik.dtu.dk/ase
  dev_url: https://gitlab.com/ase/ase

extra:
  recipe-maintainers:
    - jochym
    - CJ-Wright
