{% set name = "ase" %}
{% set version = "3.27.0" %}
{% set sha256 = "92ada752d6866a61d2d27e0e6a4fd5b8cd86f59ca79a58f1d2fe29d7099153dc" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ase=ase.cli.main:main
    - ase-db=ase.cli.main:old
    - ase-gui=ase.cli.main:old
    - ase-run=ase.cli.main:old
    - ase-info=ase.cli.main:old
    - ase-build=ase.cli.main:old

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flask
    - matplotlib-base
    - numpy
    - scipy

test:
  requires:
    - pytest
    - pytest-mock
    - python {{ python_min }}
  imports:
    - ase
  commands:
    - export DISPLAY=""   # [not win]
    - ase test


about:
  home: https://gitlab.com/ase/ase
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: ASE is a python package providing an open source Atomic Simulation Environment in the Python language.

  description: |
    ASE is a set of tools and Python modules for setting up, 
    manipulating, running, visualizing and analyzing atomistic simulations.
    Python 3.5+
  doc_url: http://wiki.fysik.dtu.dk/ase
  dev_url: https://gitlab.com/ase/ase

extra:
  recipe-maintainers:
    - jochym
    - CJ-Wright
    - jan-janssen
