travis:
  secure:
    BINSTAR_TOKEN: ZB/UgTCqY+Iwia6gvT14Y2MtaUN2nPpGKkCkhGT8AHSSr/Wqv6iuEy+2PPeAL5oP6Oovb2HDE1WsZ8YSjCXj51XzdFoCujNq3TA3x46z8QPPOsdKoTzQ+sfqmteYETi5v7hprOqPr/ufLoGmcH6YvbHNGTp4VUAVFgMob1iL6dCwKG/yovwxgtZjq6iIrV/VyB0ohFp8A2gh6TCYqDmItn3PM5vKGsI2kHZzbECcCUf5GPA3jdTQwr0xDmRa1VhJv0HsI4HRt3TxvZRxg4v4eH32u8CKSi+nxSlE1P3i/M37CDVg1ShZb6ggPHbVEvAZH4BqJNSHds44XXpkoCqLcW1xlw8wWMkcLT0ENJEsWScNzNPSe8sfViH7w9zz70xz9OHhsBUICRod0gFObBMnVssx02ffX+Di1+mud5tNzULyc+G0uxZx3+dZNJRR8P/QiIzfSt/SM8v3xNpw8H3sd0hDR9IIiBatejxzk4SySjxP93DiI+MeQiZs6op54KDD8pL0rkNaWPCa5JAy9ytBQx2kGkCIDeAPtLAgSBoVpxBB5nZ5angNubCDZiZfolEh6N+LVlNlwJYMA5rCunYpmziD3SLRH0GsiCPt81r9McNjO5jF2tkqQT3j9OG8p+I3re0AWi1i2ttaJogn5quIfBhaubPjfKD9ABIHpHlU2f8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
