travis:
  secure:
    BINSTAR_TOKEN: zh6jJYm1PUuNjPD0kji461sNHLdQDE5CIAK8bPzJCRWdYXzFbvYTt7H3MtR52C8k+AYR/X6zpMPgQyfIqAAA/4yyBUTXeW0DcsY2vmH1MKqjzK9CTeR+/CyG5kyo6LJCdeKlklnq+Q1inby0uK9VHDQSjE/mWG+ADvp6RJzjyXtIo17ft9I+X8wTDRdF3t11JvM9xGM4xxJ+UmyGuwgz/xKEdat4Ket275YyFFew/0DNPq7Szfahzjbk2k4yJ4wlvmL6dEq5D0ANF7XuC9Z6d6fKM7cxfg7ZoyJyuOb1jGJz9M18QyOvsD8e2tLsmVXDUIv0Lr4+zX/NB6i8OGnX5DOCabDtpYq5i8p2jyL6nih47YqG3y9aYuYo024vVJNLNGcgJfPX1q3hEmOpuKiYOCcBmgmxIji0UY/PaBBW2nVz6lf2iVNieeDXhOWzOWbVu0uyl/I6IOd98dSZTZLJa+7pS19QKkwGWbYY0UkXa76UBhX0yuS5iSWJMov+F184H9Y7wGNee4/KKOLH/KSRMEEbzOUXW87i3+8hv34C1+UoVHickdv1KTsmDgPBHmQDe7edGMs397lYRPk4igm/RVM6eeB6C2Jq2OAqfsKI/OdUdfw1dD+dpXviDsQzEq81J2yFukJWeZa+P2URXH3Q8PnsaZ3nZF/rRtpVmU9gOUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
